export const MASTER_DISPATCH_EVENTS = {
  GET_PRODUCTS: "GET_PRODUCTS",
  SET_PRODUCTS: "SET_PRODUCTS",
  ADD_TO_CART: "ADD_TO_CART",
  QTY_DECREMENT: "QTY_DECREMENT",
  REMOVE_ITEM_CART: "REMOVE_ITEM_CART",
  CLEAR_CART: "CLEAR_CART",
  APPLY_FILTER: "APPLY_FILTER",
};
